### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by VSciFlight** [DanielShapi4a/SafetyMap#22]
When using from a small screen the text is glitching and covering the paragraph

![image](https://github.com/DanielShapi4a/SafetyMap/assets/119410516/3a0c038c-4bb1-4074-8129-f3008ead5fa7)

Reproducing steps:
1. Enter the website
2. Change screen size width gradually 
3. Wait a little bit and see the effect

**Comment by DanielShapi4a** [comment]
Suggested changes have been made, thanks a lot and have a nice day:)
