### ISSUE TITLE
UX/UI Suggestions: reordering web elements, gradient colors for map, last update date on details

### ISSUE THREAD

**Issue by VSciFlight** [DanielShapi4a/SafetyMap#24]
UX/UI Suggestion:

Take the "Main-Text" class elements and instead of placing it in one column, spread it into four columns. It saves space and shows the main idea of the project.
Then bring the map down so it will be also closer to the "country-info-panel" class elements. When the user clicks on a country it will be clear where he needs to look at to gain the information.

Data Presentation suggestion:
The data on the map is showing danger levels: [Safe, Moderate, Danger, Immediate Danger, Multiple Warning Levels, Unknown].
It is possible to view it as scale (danger scale) and should use a gradient colors and not different colors at all.

Additional Information suggestion:
For matter of relevancy, it is recommended to add last update date on the travel warnings.

**Comment by DanielShapi4a** [comment]
I am aware of the Gradient color implementation however when i tried to work around LeafLet i had some issues using gradient colors with the map that it provides. Thus i had no choice but to keep a static color.
